[project]
name = "scaler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "pika>=1.3.2",
    "requests>=2.32.4",
    "uvicorn[standard]>=0.35.0",
]
