FROM python:3.10.12

ADD .  /home/zhou/project/test/AI-orchestrator

WORKDIR /home/zhou/project/test/AI-orchestrator

RUN pip3 install -r /home/zhou/project/test/AI-orchestrator/requirements.txt

CMD ["python", "/home/zhou/project/test/AI-orchestrator/main.py"]
